version: '3.8'

services:
  mysql-db1:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: db1
    ports:
      - "3306:3306"
    volumes:
      - mysql_db1:/var/lib/mysql
      - ./db-init-scripts/db1-init.sql:/docker-entrypoint-initdb.d/db1-init.sql
    networks:
      - my_network

  mysql-db2:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: db2
    ports:
      - "3307:3306"
    volumes:
      - mysql_db2:/var/lib/mysql
      - ./db-init-scripts/db2-init.sql:/docker-entrypoint-initdb.d/db2-init.sql
    networks:
      - my_network

  app:
    image: user-aggregator-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db1
      - mysql-db2
    networks:
      - my_network
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_DB1_URL: jdbc:mysql://mysql-db1:3306/db1
      SPRING_DATASOURCE_DB1_USERNAME: root
      SPRING_DATASOURCE_DB1_PASSWORD: testpass

      SPRING_DATASOURCE_DB2_URL: jdbc:mysql://mysql-db2:3306/db2
      SPRING_DATASOURCE_DB2_USERNAME: root
      SPRING_DATASOURCE_DB2_PASSWORD: testpass

volumes:
  mysql_db1:
    driver: local
  mysql_db2:
    driver: local

networks:
  my_network:
    driver: bridge
