spring:
  sql:
    init:
      mode: never
      continue-on-error: false
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    db1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: db1
      url:  ${SPRING_DATASOURCE_DB1_URL}
      username: ${SPRING_DATASOURCE_DB1_USERNAME}
      password: ${SPRING_DATASOURCE_DB1_PASSWORD}
      mapping:
          id: user_id
          username: login
          name: first_name
          surname: last_name
    db2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: db2
      url: ${SPRING_DATASOURCE_DB2_URL}
      username: ${SPRING_DATASOURCE_DB2_USERNAME}
      password: ${SPRING_DATASOURCE_DB2_PASSWORD}
      mapping:
        id: userId
        username: login
        name: firstName
        surname: lastName



